
#ifndef DAWN_HW_AES_REGS_H_
#define DAWN_HW_AES_REGS_H_

#include <dawn/hw/iobase.h>

#if ARM7

#define REG_AES_CNT_ADDR    (IO_AES_BASE + 0)
#define REG_AES_BLKCNT_ADDR (IO_AES_BASE + 4)
#define REG_AES_WRFIFO_ADDR (IO_AES_BASE + 8)
#define REG_AES_RDFIFO_ADDR (IO_AES_BASE +12)

#define REG_AES_IV_ADDR  (IO_AES_BASE + 0x20)
#define REG_AES_MAC_ADDR (IO_AES_BASE + 0x30)

#define REG_AES_KEY0_ADDR (IO_AES_BASE + 0x40)
#define REG_AES_KEY1_ADDR (IO_AES_BASE + 0x70)
#define REG_AES_KEY2_ADDR (IO_AES_BASE + 0xa0)
#define REG_AES_KEY3_ADDR (IO_AES_BASE + 0xd0)

#define REG_AES_KEY0X_ADDR (IO_AES_BASE + 0x50)
#define REG_AES_KEY1X_ADDR (IO_AES_BASE + 0x80)
#define REG_AES_KEY2X_ADDR (IO_AES_BASE + 0xb0)
#define REG_AES_KEY3X_ADDR (IO_AES_BASE + 0xe0)

#define REG_AES_KEY0Y_ADDR (IO_AES_BASE + 0x60)
#define REG_AES_KEY1Y_ADDR (IO_AES_BASE + 0x90)
#define REG_AES_KEY2Y_ADDR (IO_AES_BASE + 0xc0)
#define REG_AES_KEY3Y_ADDR (IO_AES_BASE + 0xf0)


#define REG_AES_CNT (*(volatile uint32_t*)REG_AES_CNT_ADDR)
#define REG_AES_BLKCNT (*(volatile uint32_t*)REG_AES_BLKCNT_ADDR)
#define REG_AES_WRFIFO (*(volatile uint32_t*)REG_AES_WRFIFO_ADDR)
#define REG_AES_RDFIFO (*(volatile uint32_t*)REG_AES_RDFIFO_ADDR)

#define REG_AES_IV ((volatile uint8_t*)REG_AES_IV_ADDR)
#define REG_AES_MAC ((volatile uint8_t*)REG_AES_MAC_ADDR)

#define REG_AES_KEY0 ((volatile uint8_t*)REG_AES_KEY0_ADDR)
#define REG_AES_KEY1 ((volatile uint8_t*)REG_AES_KEY1_ADDR)
#define REG_AES_KEY2 ((volatile uint8_t*)REG_AES_KEY2_ADDR)
#define REG_AES_KEY3 ((volatile uint8_t*)REG_AES_KEY3_ADDR)

#define REG_AES_KEY0X ((volatile uint8_t*)REG_AES_KEY0X_ADDR)
#define REG_AES_KEY1X ((volatile uint8_t*)REG_AES_KEY1X_ADDR)
#define REG_AES_KEY2X ((volatile uint8_t*)REG_AES_KEY2X_ADDR)
#define REG_AES_KEY3X ((volatile uint8_t*)REG_AES_KEY3X_ADDR)

#define REG_AES_KEY0Y ((volatile uint8_t*)REG_AES_KEY0Y_ADDR)
#define REG_AES_KEY1Y ((volatile uint8_t*)REG_AES_KEY1Y_ADDR)
#define REG_AES_KEY2Y ((volatile uint8_t*)REG_AES_KEY2Y_ADDR)
#define REG_AES_KEY3Y ((volatile uint8_t*)REG_AES_KEY3Y_ADDR)


#define REG_AES_CNT_WRFIFOCNT_Lsb     0
#define REG_AES_CNT_RDFIFOCNT_Lsb     5
#define REG_AES_CNT_WRFIFOFLUSH_Lsb  10
#define REG_AES_CNT_RDFIFOFLUSH_Lsb  11
#define REG_AES_CNT_WRFIFODMASZ_Lsb  12
#define REG_AES_CNT_RDFIFODMASZ_Lsb  14
#define REG_AES_CNT_CCMMACSZ_Lsb     16
#define REG_AES_CNT_CCMAD2FIFO_Lsb   19
#define REG_AES_CNT_CCMVERIFYSRC_Lsb 20
#define REG_AES_CNT_CCMVERIFYRES_Lsb 21
#define REG_AES_CNT_KEYSEL_Lsb       24
#define REG_AES_CNT_KEYSCHEDBUSY_Lsb 25
#define REG_AES_CNT_KEYSLOT_Lsb      26
#define REG_AES_CNT_BLOCKMODE_Lsb    28
#define REG_AES_CNT_IE_Lsb           30
#define REG_AES_CNT_ENABLE_Lsb       31

#define REG_AES_CNT_WRFIFOCNT_Msk    (0x1f<<REG_AES_CNT_WRFIFOCNT_Lsb)
#define REG_AES_CNT_RDFIFOCNT_Msk    (0x1f<<REG_AES_CNT_RDFIFOCNT_Lsb)
#define REG_AES_CNT_WRFIFOFLUSH_Msk  (1<<REG_AES_CNT_WRFIFOFLUSH_Lsb)
#define REG_AES_CNT_RDFIFOFLUSH_Msk  (1<<REG_AES_CNT_RDFIFOFLUSH_Lsb)
#define REG_AES_CNT_WRFIFODMASZ_Msk  (3<<REG_AES_CNT_WRFIFODMASZ_Lsb)
#define REG_AES_CNT_RDFIFODMASZ_Msk  (3<<REG_AES_CNT_RDFIFODMASZ_Lsb)
#define REG_AES_CNT_CCMMACSZ_Msk     (7<<REG_AES_CNT_CCMMACSZ_Lsb)
#define REG_AES_CNT_CCMAD2FIFO_Msk   (1<<REG_AES_CNT_CCMAD2FIFO_Lsb)
#define REG_AES_CNT_CCMVERIFYSRC_Msk (1<<REG_AES_CNT_CCMVERIFYSRC_Lsb)
#define REG_AES_CNT_CCMVERIFYRES_Msk (1<<REG_AES_CNT_CCMVERIFYRES_Lsb)
#define REG_AES_CNT_KEYSEL_Msk       (1<<REG_AES_CNT_KEYSEL_Lsb)
#define REG_AES_CNT_KEYSCHEDBUSY_Msk (1<<REG_AES_CNT_KEYSCHEDBUSY_Lsb)
#define REG_AES_CNT_KEYSLOT_Msk      (3<<REG_AES_CNT_KEYSLOT_Lsb)
#define REG_AES_CNT_BLOCKMODE_Msk    (3<<REG_AES_CNT_BLOCKMODE_Lsb)
#define REG_AES_CNT_IE_Msk           (1<<REG_AES_CNT_IE_Lsb)
#define REG_AES_CNT_ENABLE_Msk       (1<<REG_AES_CNT_ENABLE_Lsb)

#define REG_AES_CNT_WRFIFODMASZ_16W (0<<REG_AES_CNT_WRFIFODMASZ_Lsb)
#define REG_AES_CNT_WRFIFODMASZ_12W (1<<REG_AES_CNT_WRFIFODMASZ_Lsb)
#define REG_AES_CNT_WRFIFODMASZ_8W  (2<<REG_AES_CNT_WRFIFODMASZ_Lsb)
#define REG_AES_CNT_WRFIFODMASZ_4W  (3<<REG_AES_CNT_WRFIFODMASZ_Lsb)

#define REG_AES_CNT_RDFIFODMASZ_4W  (0<<REG_AES_CNT_RDFIFODMASZ_Lsb)
#define REG_AES_CNT_RDFIFODMASZ_8W  (1<<REG_AES_CNT_RDFIFODMASZ_Lsb)
#define REG_AES_CNT_RDFIFODMASZ_12W (2<<REG_AES_CNT_RDFIFODMASZ_Lsb)
#define REG_AES_CNT_RDFIFODMASZ_16W (3<<REG_AES_CNT_RDFIFODMASZ_Lsb)

#define REG_AES_CNT_CCMVERIFYSRC_WRFIFO (0<<REG_AES_CNT_CCMVERIFYSRC_Lsb)
#define REG_AES_CNT_CCMVERIFYSRC_MAC    (1<<REG_AES_CNT_CCMVERIFYSRC_Lsb)
#define REG_AES_CNT_CCMVERIFYRES_NOK (0<<REG_AES_CNT_CCMVERIFYRES_Lsb)
#define REG_AES_CNT_CCMVERIFYRES_OK  (1<<REG_AES_CNT_CCMVERIFYRES_Lsb)

#define REG_AES_CNT_BLOCKMODE_CCMDEC (0<<REG_AES_CNT_BLOCKMODE_Lsb)
#define REG_AES_CNT_BLOCKMODE_CCMENC (1<<REG_AES_CNT_BLOCKMODE_Lsb)
#define REG_AES_CNT_BLOCKMODE_CTR    (2<<REG_AES_CNT_BLOCKMODE_Lsb)

#endif

#endif

