
#ifndef DAWN_HW_NDMA_REGS_H_
#define DAWN_HW_NDMA_REGS_H_

#include <dawn/hw/iobase.h>


#define REG_NDMAGCNT_ADDR (IO_NDMA_BASE +  0)

#define REG_NDMAxSAD_ADDR(x)   (IO_NDMA_BASE +  4 + (x)*0x1c)
#define REG_NDMAxDAD_ADDR(x)   (IO_NDMA_BASE +  8 + (x)*0x1c)
#define REG_NDMAxTCNT_ADDR(x)  (IO_NDMA_BASE + 12 + (x)*0x1c)
#define REG_NDMAxWCNT_ADDR(x)  (IO_NDMA_BASE + 16 + (x)*0x1c)
#define REG_NDMAxBCNT_ADDR(x)  (IO_NDMA_BASE + 20 + (x)*0x1c)
#define REG_NDMAxFDATA_ADDR(x) (IO_NDMA_BASE + 24 + (x)*0x1c)
#define REG_NDMAxCNT_ADDR(x)   (IO_NDMA_BASE + 28 + (x)*0x1c)


#define REG_NDMAGCNT (*(volatile uint32_t*)REG_NDMAGCNT_ADDR)

#define REG_NDMAxSAD(x)   (*(volatile uint32_t*)REG_NDMAxSAD_ADDR(x))
#define REG_NDMAxDAD(x)   (*(volatile uint32_t*)REG_NDMAxDAD_ADDR(x))
#define REG_NDMAxTCNT(x)  (*(volatile uint32_t*)REG_NDMAxTCNT_ADDR(x))
#define REG_NDMAxWCNT(x)  (*(volatile uint32_t*)REG_NDMAxWCNT_ADDR(x))
#define REG_NDMAxBCNT(x)  (*(volatile uint32_t*)REG_NDMAxBCNT_ADDR(x))
#define REG_NDMAxFDATA(x) (*(volatile uint32_t*)REG_NDMAxFDATA_ADDR(x))
#define REG_NDMAxCNT(x)   (*(volatile uint32_t*)REG_NDMAxCNT_ADDR(x))


#define REG_NDMAGCNT_CYC_Lsb 16
#define REG_NDMAGCNT_ARB_Lsb 31

#define REG_NDMABCNT_TIMER_Lsb   0
#define REG_NDMABCNT_CLKDIV_Lsb 16

#define REG_NDMACNT_DAD_UPD_Lsb 10
#define REG_NDMACNT_DAD_RLD_Lsb 12
#define REG_NDMACNT_SAD_UPD_Lsb 13
#define REG_NDMACNT_SAD_RLD_Lsb 15
#define REG_NDMACNT_BLKSZ_Lsb   16
#define REG_NDMACNT_MODE_Lsb    24
#define REG_NDMACNT_REPEAT_Lsb  29
#define REG_NDMACNT_IE_Lsb      30
#define REG_NDMACNT_ENABLE_Lsb  31


#define REG_NDMAGCNT_CYC_Msk (15<<REG_NDMAGCNT_CYC_Lsb)
#define REG_NDMAGCNT_ARB_Msk (1<<REG_NDMAGCNT_ARB_Lsb)

#define REG_NDMABCNT_TIMER_Msk  (0xffff<<REG_NDMABCNT_TIMER_Lsb)
#define REG_NDMABCNT_CLKDIV_Msk (3<<REG_NDMABCNT_CLKDIV_Lsb)

#define REG_NDMACNT_DAD_UPD_Msk (3<<REG_NDMACNT_DAD_UPD_Lsb)
#define REG_NDMACNT_DAD_RLD_Msk (1<<REG_NDMACNT_DAD_RLD_Lsb)
#define REG_NDMACNT_SAD_UPD_Msk (3<<REG_NDMACNT_SAD_UPD_Lsb)
#define REG_NDMACNT_SAD_RLD_Msk (1<<REG_NDMACNT_SAD_RLD_Lsb)
#define REG_NDMACNT_BLKSZ_Msk   (15<<REG_NDMACNT_BLKSZ_Lsb)
#define REG_NDMACNT_MODE_Msk    (31<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_REPEAT_Msk  (1<<REG_NDMACNT_REPEAT_Lsb)
#define REG_NDMACNT_IE_Msk      (1<<REG_NDMACNT_IE_Lsb)
#define REG_NDMACNT_ENABLE_Msk  (1<<REG_NDMACNT_ENABLE_Lsb)


#define REG_NDMAGCNT_ARB_HIPRIO (0<<REG_NDMAGCNT_ARB_Lsb)
#define REG_NDMAGCNT_ARB_RROBIN (1<<REG_NDMAGCNT_ARB_Lsb)

#define REG_NDMABCNT_TIMER(x) (((x) << REG_NDMABCNT_TIMER_Lsb) & REG_NDMABCNT_TIMER_Msk)
#define REG_NDMABCNT_CLKDIV_33MHZ (0<<REG_NDMABCNT_CLKDIV_Lsb)
#define REG_NDMABCNT_CLKDIV_8MHZ  (1<<REG_NDMABCNT_CLKDIV_Lsb)
#define REG_NDMABCNT_CLKDIV_2MHZ  (2<<REG_NDMABCNT_CLKDIV_Lsb)
#define REG_NDMABCNT_CLKDIV_P5MHZ (3<<REG_NDMABCNT_CLKDIV_Lsb)

#define REG_NDMACNT_DAD_UPD_INC  (0<<REG_NDMACNT_DAD_UPD_Lsb)
#define REG_NDMACNT_DAD_UPD_DEC  (1<<REG_NDMACNT_DAD_UPD_Lsb)
#define REG_NDMACNT_DAD_UPD_FIX  (2<<REG_NDMACNT_DAD_UPD_Lsb)
#define REG_NDMACNT_SAD_UPD_INC  (0<<REG_NDMACNT_SAD_UPD_Lsb)
#define REG_NDMACNT_SAD_UPD_DEC  (1<<REG_NDMACNT_SAD_UPD_Lsb)
#define REG_NDMACNT_SAD_UPD_FIX  (2<<REG_NDMACNT_SAD_UPD_Lsb)
#define REG_NDMACNT_SAD_UPD_FILL (3<<REG_NDMACNT_SAD_UPD_Lsb)

#ifdef ARM7
#define REG_NDMACNT_MODE_TM0  ( 0<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM1  ( 1<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM2  ( 2<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM3  ( 3<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_GCD  ( 4<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_GCD2 ( 5<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_VBL  ( 6<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_NWM  ( 7<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_SDMC ( 8<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_SDIO ( 9<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_AESI (10<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_AESO (11<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_MIC  (12<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_NOW  (16<<REG_NDMACNT_MODE_Lsb)
#endif

#ifdef ARM9
#define REG_NDMACNT_MODE_TM0      ( 0<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM1      ( 1<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM2      ( 2<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_TM3      ( 3<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_GCD      ( 4<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_GCD2     ( 5<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_VBL      ( 6<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_HBL      ( 7<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_DISPSYNC ( 8<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_RAMDISP  ( 9<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_GXFIFO   (10<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_CAM      (11<<REG_NDMACNT_MODE_Lsb)
#define REG_NDMACNT_MODE_NOW      (16<<REG_NDMACNT_MODE_Lsb)
#endif

#endif

