
#ifndef DAWN_HW_PXI_REGS_H_
#define DAWN_HW_PXI_REGS_H_

#include <dawn/hw/iobase.h>


#define REG_IPCSYNC_ADDR     (IO_PXI_BASE + 0)
#define REG_IPCFIFOCNT_ADDR  (IO_PXI_BASE + 4)
#define REG_IPCFIFOSEND_ADDR (IO_PXI_BASE + 8)
#define REG_IPCFIFORECV_ADDR (IO_PXI_BASE + 0xffe80)


#define REG_IPCSYNC (*(volatile uint16_t*)REG_IPCSYNC_ADDR)
#define REG_IPCFIFOCNT (*(volatile uint16_t*)REG_IPCFIFOCNT_ADDR)
#define REG_IPCFIFOSEND (*(volatile uint32_t*)REG_IPCFIFOSEND_ADDR)
#define REG_IPCFIFORECV (*(volatile uint32_t*)REG_IPCFIFORECV_ADDR)


#define REG_IPCSYNC_FROMCPU_Lsb  0
#define REG_IPCSYNC_TOCPU_Lsb    8
#define REG_IPCSYNC_IRQXMIT_Lsb 13
#define REG_IPCSYNC_IE_Lsb      14

#define REG_IPCSYNC_FROMCPU_Msk (15<<REG_IPCSYNC_FROMCPU_Lsb)
#define REG_IPCSYNC_TOCPU_Msk   (15<<REG_IPCSYNC_TOCPU_Lsb)
#define REG_IPCSYNC_IRQXMIT_Msk (1<<REG_IPCSYNC_IRQXMIT_Lsb)
#define REG_IPCSYNC_IE_Msk      (1<<REG_IPCSYNC_IE_Lsb)


#define REG_IPCFIFOCNT_SEND_EMPTY_Lsb  0
#define REG_IPCFIFOCNT_SEND_FULL_Lsb   1
#define REG_IPCFIFOCNT_SEND_EM_IE_Lsb  2
#define REG_IPCFIFOCNT_SEND_CLEAR_Lsb  3
#define REG_IPCFIFOCNT_RECV_EMPTY_Lsb  8
#define REG_IPCFIFOCNT_RECV_FULL_Lsb   9
#define REG_IPCFIFOCNT_RECV_NE_IE_Lsb 10
#define REG_IPCFIFOCNT_FIFOERR_Lsb    14
#define REG_IPCFIFOCNT_EN_Lsb         15

#define REG_IPCFIFOCNT_SEND_EMPTY_Msk (1<<REG_IPCFIFOCNT_SEND_EMPTY_Lsb)
#define REG_IPCFIFOCNT_SEND_FULL_Msk (1<<REG_IPCFIFOCNT_SEND_FULL_Lsb)
#define REG_IPCFIFOCNT_SEND_EM_IE_Msk (1<<REG_IPCFIFOCNT_SEND_EM_IE_Lsb)
#define REG_IPCFIFOCNT_SEND_CLEAR_Msk (1<<REG_IPCFIFOCNT_SEND_CLEAR_Lsb)
#define REG_IPCFIFOCNT_RECV_EMPTY_Msk (1<<REG_IPCFIFOCNT_RECV_EMPTY_Lsb)
#define REG_IPCFIFOCNT_RECV_FULL_Msk (1<<REG_IPCFIFOCNT_RECV_FULL_Lsb)
#define REG_IPCFIFOCNT_RECV_NE_IE_Msk (1<<REG_IPCFIFOCNT_RECV_NE_IE_Lsb)
#define REG_IPCFIFOCNT_FIFOERR_Msk (1<<REG_IPCFIFOCNT_FIFOERR_Lsb)
#define REG_IPCFIFOCNT_EN_Msk (1<<REG_IPCFIFOCNT_EN_Lsb)

#endif

