
#ifndef DAWN_HW_DBG_REGS_H_
#define DAWN_HW_DBG_REGS_H_

#include <dawn/hw/iobase.h>

#define REG_DBG_NOCASH_EMUID_ADDR   (IO_DBG_NOCASH_BASE + 0x00)
#define REG_DBG_NOCASH_STROUT_ADDR  (IO_DBG_NOCASH_BASE + 0x10)
#define REG_DBG_NOCASH_STRFMT_ADDR  (IO_DBG_NOCASH_BASE + 0x14)
#define REG_DBG_NOCASH_STRFMTL_ADDR (IO_DBG_NOCASH_BASE + 0x18)
#define REG_DBG_NOCASH_CHROUT_ADDR  (IO_DBG_NOCASH_BASE + 0x1c)
#define REG_DBG_NOCASH_CLOCKS_ADDR  (IO_DBG_NOCASH_BASE + 0x20)

#define REG_DBG_NOCASH_EMUID   ((const char*)REG_DBG_NOCASH_EMUID_ADDR)
#define REG_DBG_NOCASH_STROUT  (*(volatile void**)REG_DBG_NOCASH_STROUT_ADDR)
#define REG_DBG_NOCASH_STRFMT  (*(volatile void**)REG_DBG_NOCASH_STRFMT_ADDR)
#define REG_DBG_NOCASH_STRFMTL (*(volatile void**)REG_DBG_NOCASH_STRFMTL_ADDR)
#define REG_DBG_NOCASH_CHROUT  (*(volatile uint32_t*)REG_DBG_NOCASH_CHROUT_ADDR)
#define REG_DBG_NOCASH_CLOCKS  (*(const volatile uint64_t*)REG_DBG_NOCASH_CLOCKS_ADDR)

#endif

