
#ifndef DAWN_HW_I2S_REGS_H_
#define DAWN_HW_I2S_REGS_H_

#ifndef ARM7
#error "I2S is exclusive to the ARM7"
#endif

#define REG_MIC_CNT_ADDR  (IO_MIC_BASE   + 0)
#define REG_MIC_DATA_ADDR (IO_MIC_BASE   + 4)
#define REG_SNDEXCNT_ADDR (IO_SNDEX_BASE + 0)

#define REG_MIC_CNT  (*(volatile uint16_t*)REG_MIC_CNT_ADDR)
#define REG_MIC_DATA (*(volatile uint32_t*)REG_MIC_DATA_ADDR)
#define REG_SNDEXCNT (*(volatile uint16_t*)REG_SNDEXCNT_ADDR)


#define REG_MIC_CNT_CH_DISABLE_L_Lsb  0
#define REG_MIC_CNT_CH_DISABLE_R_Lsb  1
#define REG_MIC_CNT_CLKDIV_Lsb        2
#define REG_MIC_CNT_FIFO_EMPTY_Lsb    8
#define REG_MIC_CNT_FIFO_HFULL_Lsb    9 /**< "half full" */
#define REG_MIC_CNT_FIFO_FULL_Lsb    10
#define REG_MIC_CNT_FIFO_OVERRUN_Lsb 11
#define REG_MIC_CNT_FIFO_CLEAR_Lsb   12
#define REG_MIC_CNT_IE_HFULL_Lsb     13
#define REG_MIC_CNT_IE_FULL_Lsb      14
#define REG_MIC_CNT_ENABLE_Lsb       15

#define REG_MIC_CNT_CH_DISABLE_L_Msk (1<<REG_MIC_CNT_CH_DISABLE_L_Lsb)
#define REG_MIC_CNT_CH_DISABLE_R_Msk (1<<REG_MIC_CNT_CH_DISABLE_R_Lsb)
#define REG_MIC_CNT_CLKDIV_Msk       (3<<REG_MIC_CNT_CLKDIV_Lsb)
#define REG_MIC_CNT_FIFO_EMPTY_Msk   (1<<REG_MIC_CNT_FIFO_EMPTY_Lsb)
#define REG_MIC_CNT_FIFO_HFULL_Msk   (1<<REG_MIC_CNT_FIFO_HFULL_Lsb)
#define REG_MIC_CNT_FIFO_FULL_Msk    (1<<REG_MIC_CNT_FIFO_FULL_Lsb)
#define REG_MIC_CNT_FIFO_OVERRUN_Msk (1<<REG_MIC_CNT_FIFO_OVERRUN_Lsb)
#define REG_MIC_CNT_FIFO_CLEAR_Msk   (1<<REG_MIC_CNT_FIFO_CLEAR_Lsb)
#define REG_MIC_CNT_IE_HFULL_Msk     (1<<REG_MIC_CNT_IE_HFULL_Lsb)
#define REG_MIC_CNT_IE_FULL_Msk      (1<<REG_MIC_CNT_IE_FULL_Lsb)
#define REG_MIC_CNT_ENABLE_Msk       (1<<REG_MIC_CNT_ENABLE_Lsb)

#define REG_MIC_CNT_CLKDIV_1 (0<<REG_MIC_CNT_CLKDIV_Lsb)
#define REG_MIC_CNT_CLKDIV_2 (1<<REG_MIC_CNT_CLKDIV_Lsb)
#define REG_MIC_CNT_CLKDIV_3 (2<<REG_MIC_CNT_CLKDIV_Lsb)
#define REG_MIC_CNT_CLKDIV_4 (3<<REG_MIC_CNT_CLKDIV_Lsb)


#define REG_MIC_DATA_FIRST_Lsb   0
#define REG_MIC_DATA_SECOND_Lsb 16

#define REG_MIC_DATA_FIRST_Msk  (0xffffu<<REG_MIC_DATA_FIRST_Lsb)
#define REG_MIC_DATA_SECOND_Msk (0xffffu<<REG_MIC_DATA_SECOND_Lsb)


#define REG_SNDEXCNT_RATIO_Lsb   0
#define REG_SNDEXCNT_I2SCLK_Lsb 13 /**< affects entire I2S interface (i.e. both mic in and sound out) */
#define REG_SNDEXCNT_MUTE_Lsb   14 /**< "mute WHAT?" doesn't mute mic at least */
#define REG_SNDEXCNT_I2SEN_Lsb  15 /**< enable/disable entire I2S interface (i.e. both mic in and sound out) */

#define REG_SNDEXCNT_RATIO_Msk  (0xf<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_I2SCLK_Msk (1<<REG_SNDEXCNT_I2SCLK_Lsb)
#define REG_SNDEXCNT_MUTE_Msk   (1<<REG_SNDEXCNT_MUTE_Lsb)
#define REG_SNDEXCNT_I2SEN_Msk  (1<<REG_SNDEXCNT_I2SEN_Lsb)

#define REG_SNDEXCNT_RATIO_DSP8_NTR0 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP7_NTR1 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP6_NTR2 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP5_NTR3 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP4_NTR4 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP3_NTR5 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP2_NTR6 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP1_NTR7 (0<<REG_SNDEXCNT_RATIO_Lsb)
#define REG_SNDEXCNT_RATIO_DSP0_NTR8 (0<<REG_SNDEXCNT_RATIO_Lsb)

#define REG_SNDEXCNT_I2SCLK_32KHZ (0<<REG_SNDEXCNT_I2SCLK_Lsb)
#define REG_SNDEXCNT_I2SCLK_47KHZ (1<<REG_SNDEXCNT_I2SCLK_Lsb)

#endif

