
#ifndef DAWN_HW_VIDEO_REGS_H_
#define DAWN_HW_VIDEO_REGS_H_

#include <dawn/hw/iobase.h>


#define REG_DISPSTAT_ADDR (IO_PPUA_BASE + 4)
#define REG_VCOUNT_ADDR   (IO_PPUA_BASE + 6)

#define REG_DISPSTAT (*(volatile uint16_t*)REG_DISPSTAT_ADDR)
#define REG_VCOUNT   (*(volatile uint16_t*)REG_VCOUNT_ADDR)


#define REG_DISPSTAT_VBL_Lsb 0
#define REG_DISPSTAT_HBL_Lsb 1
#define REG_DISPSTAT_VCM_Lsb 2
#define REG_DISPSTAT_VIE_Lsb 3
#define REG_DISPSTAT_HIE_Lsb 4
#define REG_DISPSTAT_CIE_Lsb 5
#define REG_DISPSTAT_RDY_Lsb 6
#define REG_DISPSTAT_LY8_Lsb 7
#define REG_DISPSTAT_LYC_Lsb 8

#define REG_DISPSTAT_VBL_Msk (1<<REG_DISPSTAT_VBL_Lsb)
#define REG_DISPSTAT_HBL_Msk (1<<REG_DISPSTAT_HBL_Lsb)
#define REG_DISPSTAT_VCM_Msk (1<<REG_DISPSTAT_VCM_Lsb)
#define REG_DISPSTAT_VIE_Msk (1<<REG_DISPSTAT_VIE_Lsb)
#define REG_DISPSTAT_HIE_Msk (1<<REG_DISPSTAT_HIE_Lsb)
#define REG_DISPSTAT_CIE_Msk (1<<REG_DISPSTAT_CIE_Lsb)
#define REG_DISPSTAT_RDY_Msk (1<<REG_DISPSTAT_RDY_Lsb)
#define REG_DISPSTAT_LY8_Msk (1<<REG_DISPSTAT_LY8_Lsb)
#define REG_DISPSTAT_LYC_Msk (0xff<<REG_DISPSTAT_LYC_Lsb)


#ifdef ARM9
#define REG_DISP3DCNT_ADDR      (IO_PPUA_BASE + 0x60)
#define REG_DISPCAPCNT_ADDR     (IO_PPUA_BASE + 0x64)
#define REG_DISP_MMEM_FIFO_ADDR (IO_PPUA_BASE + 0x68)

#define REG_DISP3DCNT      (*(volatile uint16_t*)REG_DISP3DCNT_ADDR)
#define REG_DISPCAPCNT     (*(volatile uint32_t*)REG_DISPCAPCNT_ADDR)
#define REG_DISP_MMEM_FIFO (*(volatile uint32_t*)REG_DISP_MMEM_FIFO_ADDR)


#define REG_DISP3DCNT_TEX_EN_Lsb 0
#define REG_DISP3DCNT_SHADING_Lsb 1
#define REG_DISP3DCNT_ALPHATEST_Lsb 2
#define REG_DISP3DCNT_ALPHABLEND_Lsb 3
#define REG_DISP3DCNT_ANTIALIAS_Lsb 4
#define REG_DISP3DCNT_EDGEMARK_Lsb 5
#define REG_DISP3DCNT_FOGACOL_Lsb 6
#define REG_DISP3DCNT_FOG_EN_Lsb 7
#define REG_DISP3DCNT_FOG_DEPTH_Lsb 8
#define REG_DISP3DCNT_RDLINES_UDF_Lsb 12
#define REG_DISP3DCNT_VTXRAM_OVF_Lsb 13
#define REG_DISP3DCNT_REARPLANE_Lsb 14

#define REG_DISP3DCNT_TEX_EN_Msk      (1<<REG_DISP3DCNT_TEX_EN_Lsb)
#define REG_DISP3DCNT_SHADING_Msk     (1<<REG_DISP3DCNT_SHADING_Lsb)
#define REG_DISP3DCNT_ALPHATEST_Msk   (1<<REG_DISP3DCNT_ALPHATEST_Lsb)
#define REG_DISP3DCNT_ALPHABLEND_Msk  (1<<REG_DISP3DCNT_ALPHABLEND_Lsb)
#define REG_DISP3DCNT_ANTIALIAS_Msk   (1<<REG_DISP3DCNT_ANTIALIAS_Lsb)
#define REG_DISP3DCNT_EDGEMARK_Msk    (1<<REG_DISP3DCNT_EDGEMARK_Lsb)
#define REG_DISP3DCNT_FOGACOL_Msk     (1<<REG_DISP3DCNT_FOGACOL_Lsb)
#define REG_DISP3DCNT_FOG_EN_Msk      (1<<REG_DISP3DCNT_FOG_EN_Lsb)
#define REG_DISP3DCNT_FOG_DEPTH_Msk   (15<<REG_DISP3DCNT_FOG_DEPTH_Lsb)
#define REG_DISP3DCNT_RDLINES_UDF_Msk (1<<REG_DISP3DCNT_RDLINES_UDF_Lsb)
#define REG_DISP3DCNT_VTXRAM_OVF_Msk  (1<<REG_DISP3DCNT_VTXRAM_OVF_Lsb)
#define REG_DISP3DCNT_REARPLANE_Msk   (1<<REG_DISP3DCNT_REARPLANE_Lsb)


#define REG_DISPCAPCNT_EVA_Lsb      0
#define REG_DISPCAPCNT_EVB_Lsb      8
#define REG_DISPCAPCNT_VRAMSEL_Lsb 16
#define REG_DISPCAPCNT_VRAMOFF_Lsb 18
#define REG_DISPCAPCNT_CAPSIZE_Lsb 20
#define REG_DISPCAPCNT_SRCA_Lsb    24
#define REG_DISPCAPCNT_SRCB_Lsb    25
#define REG_DISPCAPCNT_READOFF_Lsb 26
#define REG_DISPCAPCNT_CAPSRC_Lsb  29
#define REG_DISPCAPCNT_EN_Lsb      31

#define REG_DISPCAPCNT_EVA_Msk     (31<<REG_DISPCAPCNT_EVA_Lsb)
#define REG_DISPCAPCNT_EVB_Msk     (31<<REG_DISPCAPCNT_EVB_Lsb)
#define REG_DISPCAPCNT_VRAMSEL_Msk (3<<REG_DISPCAPCNT_VRAMSEL_Lsb)
#define REG_DISPCAPCNT_VRAMOFF_Msk (3<<REG_DISPCAPCNT_VRAMOFF_Lsb)
#define REG_DISPCAPCNT_CAPSIZE_Msk (3<<REG_DISPCAPCNT_CAPSIZE_Lsb)
#define REG_DISPCAPCNT_SRCA_Msk    (1<<REG_DISPCAPCNT_SRCA_Lsb)
#define REG_DISPCAPCNT_SRCB_Msk    (1<<REG_DISPCAPCNT_SRCB_Lsb)
#define REG_DISPCAPCNT_READOFF_Msk (3<<REG_DISPCAPCNT_READOFF_Lsb)
#define REG_DISPCAPCNT_CAPSRC_Msk  (3<<REG_DISPCAPCNT_CAPSRC_Lsb)
#define REG_DISPCAPCNT_EN_Msk      (1<<REG_DISPCAPCNT_EN_Lsb)

#define REG_DISPCAPCNT_VRAMSEL_A (0<<REG_DISPCAPCNT_VRAMSEL_Lsb)
#define REG_DISPCAPCNT_VRAMSEL_B (1<<REG_DISPCAPCNT_VRAMSEL_Lsb)
#define REG_DISPCAPCNT_VRAMSEL_C (2<<REG_DISPCAPCNT_VRAMSEL_Lsb)
#define REG_DISPCAPCNT_VRAMSEL_D (3<<REG_DISPCAPCNT_VRAMSEL_Lsb)

#define REG_DISPCAPCNT_CAPSIZE_128x128 (0<<REG_DISPCAPCNT_CAPSIZE_Lsb)
#define REG_DISPCAPCNT_CAPSIZE_256x64  (1<<REG_DISPCAPCNT_CAPSIZE_Lsb)
#define REG_DISPCAPCNT_CAPSIZE_256x128 (2<<REG_DISPCAPCNT_CAPSIZE_Lsb)
#define REG_DISPCAPCNT_CAPSIZE_256x192 (3<<REG_DISPCAPCNT_CAPSIZE_Lsb)

#define REG_DISPCAPCNT_SRCA_PPUA (0<<REG_DISPCAPCNT_SRCA_Lsb)
#define REG_DISPCAPCNT_SRCA_GPU  (1<<REG_DISPCAPCNT_SRCA_Lsb)

#define REG_DISPCAPCNT_SRCB_VRAM (0<<REG_DISPCAPCNT_SRCB_Lsb)
#define REG_DISPCAPCNT_SRCB_FIFO (1<<REG_DISPCAPCNT_SRCB_Lsb)

#define REG_DISPCAPCNT_CAPSRC_SRCA  (0<<REG_DISPCAPCNT_CAPSRC_Lsb)
#define REG_DISPCAPCNT_CAPSRC_SRCB  (1<<REG_DISPCAPCNT_CAPSRC_Lsb)
#define REG_DISPCAPCNT_CAPSRC_SRCAB (2<<REG_DISPCAPCNT_CAPSRC_Lsb)

#define REG_DISPCAPCNT_EN (1<<REG_DISPCAPCNT_EN_Lsb)


#define REG_DISPCNT_A_ADDR       (IO_PPUA_BASE + 0x00)
#define REG_DISPCNT_B_ADDR       (IO_PPUB_BASE + 0x00)
#define REG_MASTER_BRIGHT_A_ADDR (IO_PPUA_BASE + 0x6c)
#define REG_MASTER_BRIGHT_B_ADDR (IO_PPUB_BASE + 0x6c)

#define REG_DISPCNT_A       (*(volatile uint32_t*)REG_DISPCNT_A_ADDR)
#define REG_DISPCNT_B       (*(volatile uint32_t*)REG_DISPCNT_B_ADDR)
#define REG_MASTER_BRIGHT_A (*(volatile uint16_t*)REG_MASTER_BRIGHT_A_ADDR)
#define REG_MASTER_BRIGHT_B (*(volatile uint16_t*)REG_MASTER_BRIGHT_B_ADDR)


#define REG_DISPCNT_BGMODE_Lsb 0
#define REG_DISPCNT_3DMODE_Lsb 3 /**< PPU A only */
#define REG_DISPCNT_TILEOBJMAP_Lsb 4
#define REG_DISPCNT_BMOBJ2D_Lsb 5
#define REG_DISPCNT_BMOBJMAP_Lsb 6
#define REG_DISPCNT_FBLANK_Lsb 7
#define REG_DISPCNT_BG0EN_Lsb 8
#define REG_DISPCNT_BG1EN_Lsb 9
#define REG_DISPCNT_BG2EN_Lsb 10
#define REG_DISPCNT_BG3EN_Lsb 11
#define REG_DISPCNT_OBJEN_Lsb 12
#define REG_DISPCNT_WIN0EN_Lsb 13
#define REG_DISPCNT_WIN1EN_Lsb 14
#define REG_DISPCNT_OBJWIN_Lsb 15
#define REG_DISPCNT_DISPMODE_Lsb 16
#define REG_DISPCNT_VRAMSEL_Lsb 18 /**< PPU A only */
#define REG_DISPCNT_TILEOBJ1D_Lsb 20
#define REG_DISPCNT_BMOBJ1D_Lsb 22 /**< PPU A only */
#define REG_DISPCNT_HBLOBJ_Lsb 23
#define REG_DISPCNT_CHRBASE_Lsb 24 /**< PPU A only */
#define REG_DISPCNT_SCNBASE_Lsb 27 /**< PPU A only */
#define REG_DISPCNT_BGEXTPAL_Lsb 30
#define REG_DISPCNT_OBJEXTPAL_Lsb 31

#define REG_DISPCNT_BGMODE_Msk (7<<REG_DISPCNT_BGMODE_Lsb)
#define REG_DISPCNT_3DMODE_Msk (1<<REG_DISPCNT_3DMODE_Lsb)
#define REG_DISPCNT_TILEOBJMAP_Msk (1<<REG_DISPCNT_TILEOBJMAP_Lsb)
#define REG_DISPCNT_BMOBJ2D_Msk (1<<REG_DISPCNT_BMOBJ2D_Lsb)
#define REG_DISPCNT_BMOBJMAP_Msk (1<<REG_DISPCNT_BMOBJMAP_Lsb)
#define REG_DISPCNT_FBLANK_Msk (1<<REG_DISPCNT_FBLANK_Lsb)
#define REG_DISPCNT_BG0EN_Msk (1<<REG_DISPCNT_BG0EN_Lsb)
#define REG_DISPCNT_BG1EN_Msk (1<<REG_DISPCNT_BG1EN_Lsb)
#define REG_DISPCNT_BG2EN_Msk (1<<REG_DISPCNT_BG2EN_Lsb)
#define REG_DISPCNT_BG3EN_Msk (1<<REG_DISPCNT_BG3EN_Lsb)
#define REG_DISPCNT_OBJEN_Msk (1<<REG_DISPCNT_OBJEN_Lsb)
#define REG_DISPCNT_WIN0EN_Msk (1<<REG_DISPCNT_WIN0EN_Lsb)
#define REG_DISPCNT_WIN1EN_Msk (1<<REG_DISPCNT_WIN1EN_Lsb)
#define REG_DISPCNT_OBJWIN_Msk (1<<REG_DISPCNT_OBJWIN_Lsb)
#define REG_DISPCNT_DISPMODE_Msk (3<<REG_DISPCNT_DISPMODE_Lsb)
#define REG_DISPCNT_VRAMSEL_Msk (3<<REG_DISPCNT_VRAMSEL_Lsb)
#define REG_DISPCNT_TILEOBJ1D_Msk (3<<REG_DISPCNT_TILEOBJ1D_Lsb)
#define REG_DISPCNT_BMOBJ1D_Msk (1<<REG_DISPCNT_BMOBJ1D_Lsb)
#define REG_DISPCNT_HBLOBJ_Msk (1<<REG_DISPCNT_HBLOBJ_Lsb)
#define REG_DISPCNT_CHRBASE_Msk (7<<REG_DISPCNT_CHRBASE_Lsb)
#define REG_DISPCNT_SCNBASE_Msk (7<<REG_DISPCNT_SCNBASE_Lsb)
#define REG_DISPCNT_BGEXTPAL_Msk (1<<REG_DISPCNT_BGEXTPAL_Lsb)
#define REG_DISPCNT_OBJEXTPAL_Msk (1<<REG_DISPCNT_OBJEXTPAL_Lsb)

#define REG_MASTER_BRIGHT_FACTOR_Lsb 0
#define REG_MASTER_BRIGHT_MODE_Lsb 14

#define REG_MASTER_BRIGHT_FACTOR_Msk (31<<REG_MASTER_BRIGHT_FACTOR_Lsb)
#define REG_MASTER_BRIGHT_MODE_Msk (3<<REG_MASTER_BRIGHT_MODE_Lsb)

#define REG_MASTER_BRIGHT_MODE_DISABLE (0<<REG_MASTER_BRIGHT_MODE_Lsb)
#define REG_MASTER_BRIGHT_MODE_UP      (1<<REG_MASTER_BRIGHT_MODE_Lsb)
#define REG_MASTER_BRIGHT_MODE_DOWN    (2<<REG_MASTER_BRIGHT_MODE_Lsb)
#endif /* ARM9 */

#endif

